# This workflow will do a clean install of node dependencies, cache/restore them, build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sending News

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: node dist/src/main.js
    - run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "🐱 GitHub Actions CRON" || exit 0
        git push
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
